server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # Strictly redirect /docs to /docs/ to prevent VitePress router crash
    location = /docs {
        return 301 /docs/;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # Explicitly serve Sitemap and other XML files
    location ~* \.xml$ {
        default_type application/xml;
        try_files $uri =404;
        access_log off;
        log_not_found off;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
